### ISSUE TITLE
how will it work on TV's with speakers set to Off ?

### ISSUE THREAD

**Issue by ghost** [fguchelaar/homebridge-panasonictv#2]
My TV has the speakers disabled as i use a sonos playbar for sound, will this affect the response as the speakers are always set to 0 on the tv

**Comment by fguchelaar** [comment]
I assume hou haven't tried it yet?

I'm **guessing** that it depends on how you have configured your television. My parents actually have a similar setup. Iirc they used some 'hidden' menu-option that turns the volume of their Sonos Playbar up and down, when they use the stock remote control. I figure that setting the volume through the http-api would mimic the behavior of the remote. 

Give it a go :-)

**Comment by ghost** [comment]
ok so i tried it and ... success!
i have a TX-48AX630E, it turns it off, **and on** which is more than the other plugin did... bonus!
the volume is ignored on my TV, the channel item is  weird, its a slider from 1-100 and i can't seem to work out how the channel are changed, if i select a channel it does change to that channel but obviously limited to 1-100
do you have any idea how i would use siri to change channels ?
i also did the hidden menu option but that didn't seem to make a difference so mine is just switched off in the normal menu and the songs setup with the normal remote.

**Comment by ghost** [comment]
i have found one issue, if i switch off with the remote control the app does not show the TV is off, the power is still shown as on and the log shows

```
setOn: 0
request ended
400
setOn :: Got powerstate: -1
==========================
```

**Comment by fguchelaar** [comment]
> do you have any idea how i would use siri to change channels 

If I remember correctly, this is not easily achieved while keeping the "speech-interface" intuitive. 
There is a limited set of Siri Commands that you can use in combination with Home Kit and sadly controlling _Volume_ or _Channel_ is not part of it. What you could do, is make the _Channel_ a _Brightness characteristic_, then you're basically faking Siri/Home Kit.
See here for a list of supported commands: https://support.apple.com/en-us/HT204893

With regard to the issue: nothing seems to happen, because in your Home Kit app, the button/switch you press tries to turn the tv _off_, since it still thinks its _on_. What happens if you refresh the App? Is the state correct then?

**Comment by ghost** [comment]
i removed all my accessories and persist data and it seems to work now, shame about the channel item, thats probably the most useful part i would need :-)
thanks
