### ISSUE TITLE
Installing with NPM

### ISSUE THREAD

**Issue by LukeTim** [fguchelaar/homebridge-panasonictv#3]
Hi, how can I install this package with NPM? The only package that seems to get installed is TG908's branch which lacks the volume and channel select...

**Comment by fguchelaar** [comment]
at the time of developing this fork, I was in contact with TG908 about merging these changes back to his repo. But somehow we never finished the work. Let me see if I can manage this, or otherwise I'll find out how to add this fork to NPM. Might take me a couple of days to get to it (at a course the entire week)

**Comment by m4nd00** [comment]
Hi, I would also love to be able to install through npm, thanks for the hard work on this.

**Comment by LukeTim** [comment]
@fguchelaar Thanks!

**Comment by fguchelaar** [comment]
I've left a comment for the original repo here: https://github.com/TG908/homebridge-panasonictv/issues/2. Hopefully we can finish the work, otherwise I'll figure something else out.

**Comment by fguchelaar** [comment]
We've managed to merge the repo's and a new version is available through npm. If you can let us/me know what model you have (and verify the plugin works), I can add it to the list of supported devices.
